[build]
  command = "npm run build"
  functions = "build-lambda"
  publish = "build/"
[template.environment]
  API_KEY="Set your OpenWeather API key"
  CORS_WHITELIST="Optional comma-separated list of allowed cross-origin domains"

