export const WeatherIconMapping: { [key: string]: string } = {
  "01d": "clear",
  "01n": "clear-night",
  "02d": "partly-cloudy",
  "02n": "partly-cloudy-night",
  "03d": "cloudy",
  "03n": "cloudy",
  "04d": "cloudy",
  "04n": "cloudy",
  "09d": "shower-rain",
  "09n": "shower-rain",
  "10d": "rain",
  "10n": "rain-night",
  "11d": "thunder",
  "11n": "thunder",
  "13d": "snow",
  "13n": "snow",
  "50d": "mist",
  "50n": "mist",
};
